###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    # mailhog:
    #   image: mailhog/mailhog:latest
    #   container_name: app-env-mailhog
    #   ports:
    #     - "1080:8025"
    maildev:
      image: djfarrelly/maildev
      ports:
        - "1080:80"
        - "1025:25"

    mysql:
      image: mysql:5.7
      container_name: app-env-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=elk
        - MYSQL_USER=username
        - MYSQL_PASSWORD=password
      ports:
        - "1082:3306"

    webserver:
      image: nginx:alpine
      container_name: app-env-webserver
      working_dir: /application
      volumes:
          - .:/application #:cached
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      ports:
        - "8080:80"
      depends_on:
        - "mysql"
      environment:
        PMA_HOST: mysql

    php-fpm:
      build: phpdocker/php-fpm
      container_name: app-env-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    
    elasticsearch:
      image: elasticsearch:6.5.0
      ports:
        - "9200:9200"
